apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-ssd-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/shashank/ssd"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-ssd-pvc
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
